### ISSUE TITLE
Adicionar a banner principal no README.md

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/CalenDog#22]
Adicionar a identidade visual da aplicação no README.md

![Image](https://user-images.githubusercontent.com/55944691/231309283-e9935db0-f345-4bd0-88a4-9629eb213f5c.png)

verificar com o @AntonioCaiodev o banner oficial, esse banner deve ficar no começo do arquivo

**Comment by mikaelmonteirodev** [comment]
E aí my friends @AntonioCaiodev @JuniorGildo conforme o que foi deliberado ontem, acredito que deverá ficar mais menos assim assim:

<hr>

![Image](https://user-images.githubusercontent.com/55944691/231309283-e9935db0-f345-4bd0-88a4-9629eb213f5c.png)


# CalenDog

- [Sobre](#sobre)
- [Tecnologias usadas](#tecnologias-usadas)
- [Pré-Requisitos](#pré-requisitos)
- [Como baixar o projeto](#como-baixar-o-projeto)
- [Instalação](#instalação)
- [Uso](#uso)
- [Contribuição](#contribuição)

## Sobre

<div>
  <h1 align="center">🚧 Projeto em construção 🚧</h1>
 
  **CalenDog é um dos projetos finais para turma 07 do curso de FullStack da Digital College. Nele os alunos irão apresentar seus conhecimentos e aprimorar habilidades para trabalhar, analisar e desenvolver projetos em equipe.**
  
  <p>
    <strong>CalenDog</strong> tem como objetivo desenvolver um formulário para otimizar processos e serviços para petshops.
Ele será vinculado à APIs de calendários e mensagens instantâneas. Desse modo criar uma....

### ...E aqui todo o restante do conteúdo do Readme...

**Comment by KevinDik** [comment]
@mikaelmonteirodev @AntonioCaiodev @alanafilgueiras Talvez possamos centralizar essa imagem ou colocar ela em 100% de largura?!

**Comment by alanafilgueiras** [comment]
> @mikaelmonteirodev @fabrjcio @alanafilgueiras Talvez possamos centralizar essa imagem ou colocar ela em 100% de largura?!

Eu gosto de 100% e outra ideia que poderia ser aplicada é inserir no banner um calendario ou alguma coisa que lembrasse um agendamento.

**Comment by mikaelmonteirodev** [comment]
@KevinDik  Tipo isso, só que com um novo Banner, modificado com a sugestão da @alanafilgueiras, certo?

<h1 align="center">
  <p align="center">Calendog</p>
  <a href="https://docusaurus.io"><img src="https://user-images.githubusercontent.com/55944691/231309283-e9935db0-f345-4bd0-88a4-9629eb213f5c.png" alt="CalenDog"></a>
</h1>

**Comment by KevinDik** [comment]
Sim, poderiamos montar o banner com uma imagem do calendario ao lado, na minha opiniao ja seria ate mais interessante que manter o titulo, sendo assim podemos tirar o titulo e deixar so o banner, ficaria muito mais clean. O que acha @alanafilgueiras ?
