### ISSUE TITLE
Descrever os pre-requisitos do README.md

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/CalenDog#3]
## Pre-requisitos

Deverá informar qual será as ferramentas que precisam ser baixadas e como baixar o projeto.

### Exemplo:

- Informar as tecnologias que deverão ser baixadas com os links

NodeJS: ![NodeJS](https://img.shields.io/badge/node.js-6DA55F?style=for-the-badge&logo=node.js&logoColor=white)
VisualStudio: ![Visual Studio Code](https://img.shields.io/badge/Visual%20Studio%20Code-0078d7.svg?style=for-the-badge&logo=visual-studio-code&logoColor=white)

**Comment by AbraaoAlves** [comment]
Add 

- Git 
- MDX Extension no VSCODE

**Comment by AbraaoAlves** [comment]
> Precisa informar os links para os tutoriais de instalação cada ferramenta
