### ISSUE TITLE
Descrição do projeto no README.md

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/CalenDog#4]
<div>
  <h1 align="center">🚧 Projeto em construção 🚧</h1>
 
  **CalenDog é um dos projetos finais para turma 07 do curso de FullStack da Digital College. Nele os alunos irão apresentar seus conhecimentos e aprimorar habilidades para trabalhar, analisar e desenvolver projetos em equipe.**
  
  <p>
    <strong>CalenDog</strong> projeto que tem como objetivo desenvolver um formulário para otimizar processos e serviços para petshops.
Ele será vinculado à APIs de calendários e mensagens instantâneas. Desse modo criar uma melhor relação do petshop 
com seu cliente. 📆
     
   
  </p>

![Image](https://user-images.githubusercontent.com/112489062/230792165-150fe0bf-cb3a-4b52-85fd-d48ee38e206f.svg)

</div>

**Comment by alanafilgueiras** [comment]
## Descrição
**CalenDog** é um projeto de curso da turma de FullStack da Digital College. O CalenDog é um formulário e tem como finalidade o agendamento de serviços pet (banho, tosa, vacina) para petshop. O projeto será vinculado à APIs de calendário e mensagem instantanea. É uma forma facilitada e comoda de gerenciar e organizar o serviço :calendar:

![Badge em Desenvolvimento](http://img.shields.io/static/v1?label=STATUS&message=EM%20DESENVOLVIMENTO&color=GREEN&style=for-the-badge) @JoelRamosdev aqui é um exemplo do que q é o calendog, se quiser adicionar mais coisa pode ficar à vontade. @AbraaoAlves to te marcando pra ver se você concorda com a descrição ou se tem mais alguma coisa pra acrescentar

**Comment by KevinDik** [comment]
No escopo do README.md acho que seria interessante ter a logo do projeto

**Comment by AbraaoAlves** [comment]
@JoelRamosdev você precisa colocar o conteúdo em um branch, editando o arquivo de README.md e criar uma PullRequest atrelada a essa issue
