### ISSUE TITLE
#CalenDog Como fazer deploy documentação do README.md

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/CalenDog#7]
### Exemplo: 

- Como subir para o github pages

**Comment by KevinDik** [comment]
Link explicando mais sobre como fazer deploy

https://www.alura.com.br/artigos/como-colocar-projeto-no-ar-com-github-pages?gclid=Cj0KCQjw27mhBhC9ARIsAIFsETEB4TMP7NvSBq4jJGo_6KHjSnkmyMuYUZ71xnr0hNW862ixcBWyOrIaArIMEALw_wcB

**Comment by mikaelmonteirodev** [comment]
@AlexandreDEVNunes Aqui tb um exemplo de como foi feito no projeto In_Progress [PR#23](https://github.com/dcTeam7/in_progress/pull/23/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
