### ISSUE TITLE
#CalenDog Contribuidores documentação do README.md

### ISSUE THREAD

**Issue by kevinDsousa** [dcTeam7/CalenDog#8]
## Descrever os contribuidores do projeto com links de cada github

![Image](https://user-images.githubusercontent.com/55944691/229918870-39f1586a-7c69-4c8e-a8c3-3cad076ab700.png)

**Comment by fabrjcio** [comment]
Exemplo: https://github.com/kentcdodds/advanced-react-hooks#contributors

**Comment by KevinDik** [comment]
Fabricio
A alana colocou uma documentação onde tambem ha um exemplo interessante para se  inspirar

![contribuicoes](https://user-images.githubusercontent.com/55944691/230469628-69665ae8-6b1e-4618-ab08-f50d97c7807c.png)

https://github.com/facebook/docusaurus#readme

**Comment by mikaelmonteirodev** [comment]
Fala @fabrjcio ! Minha sugestão para inclusão dos avatares dos contribuidores do projeto é a seguinte:

```
# Contribuidores

[![Contributors](https://contributors-img.web.app/image?repo=dcteam7/calendog)](https://github.com/dcteam7/calendog/graphs/contributors)
```

Desta forma, ele inclui dinamicamente os avatares de quem contribuiu com o projeto.
Abraço!

**Comment by fabrjcio** [comment]
Valeu @mikaelmonteirodev aderi a sugestão! 👍🏻

**Comment by fabrjcio** [comment]
@KevinDik @AbraaoAlves vamos iniciar trazendo a imagem do contribuidor, sugerido pelo Mikael, que é um processo mais simples. Mais na frente atualizo pra puxar o link do github do mesmo, emojis e etc. É um bot que faz esse trabalho, em um projeto chamado all-contributors [https://github.com/all-contributors/all-contributors]

Se houver outra forma de puxar o link do github dos perfis dos contribuidores, me atualizem!
