### ISSUE TITLE
#CalenDog Criar um Figma do projeto calendog

### ISSUE THREAD

**Issue by KevinDik** [dcTeam7/CalenDog#9]
## Criar o Figma do projeto

Criar o figma do projeto contendo suas telas, padrões de cores, tamanhos de fontes e fontes especificas

- [x] Ao criar, inserir o Link aqui

**Comment by AntonioCaiodev** [comment]
Prezados, segue o link do protótipo no Figma. Lembrando que é uma primeira versão e está passível de alterações, então sintam-se a vontade para sugerir melhorias. 

Existem alguns balões de comentários que são pertinentes para o projeto. 

https://www.figma.com/file/ZGbXCfSMwOjQ0Fozu9nYk6/PROT%C3%93TIPO-TESTE---TELA-CALENDOG?node-id=0%3A1&t=KRbdRlyoFM2ihUiy-1


Segue aqui também o link do protótipo:

https://www.figma.com/proto/ZGbXCfSMwOjQ0Fozu9nYk6/PROT%C3%93TIPO-TESTE---TELA-CALENDOG?page-id=0%3A1&node-id=83-219&viewport=457%2C819%2C0.26&scaling=contain

O fluxo do sistema é simples, no protótipo percebe-se bem.

Quanto ao styleguide, a paleta de cores e a tipografia estão contempladas no arquivo. A paleta é simples e a tipografia limitou-se a uma fonte só.

Dúvidas e sugestões, estou à disposição.

@KevinDik @AbraaoAlves

**Comment by KevinDik** [comment]
Boa analisar o figma para poder extrair alguns entregavéis, obrigado Caio

**Comment by alanafilgueiras** [comment]
Como foi dito antes a parte dos serviços tem que adicionar e acho que também poderia ter alguns campos so pro pet. Tipo: idade, espécie...

**Comment by KevinDik** [comment]
Vamos colocar o link do Figma no README.md?

**Comment by AbraaoAlves** [comment]
Vocês podem criar uma PR colocando o print do figma no ReadME.

Recomendo que o @AntonioCaiodev faça isso.

**Comment by mikaelmonteirodev** [comment]
Grande @AntonioCaiodev vou auxiliar vc nesta tarefa. 👍
